# Generated by Django 3.2.9 on 2021-11-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('reading', models.FloatField()),
                ('device_id', models.UUIDField()),
                ('customer_id', models.UUIDField()),
            ],
        ),
    ]
